apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: prometheus.terop-kuber.com
    http:
      paths:
      - backend:
          serviceName: prometheus-server-alb
          servicePort: 80
        path: /
