apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask01-ingress
  namespace: flask
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: flask01.terop-kuber.com
    http:
      paths:
      - backend:
          serviceName: flask01-service
          servicePort: 80
        path: /
